# === Friends-Communicator ===
# 3x 8x8 MAX7219 matrix + rotary encoder attached to ESP32 C3 SuperMini
# Created: 30.01.2026
#
# https://esphome.io/components/display/max7219digit/

# GPIO2/D0 is a strapping pin
substitutions:
  display_pin_din:   GPIO5  # D3, yellow
  display_pin_cs:    GPIO6  # D4, green
  display_pin_clk:   GPIO7  # D5, white
  display_intensity: 3      # 0...15


esphome:
  name: esphome-communicator
  friendly_name: Communicator
  comment: Send emoji to friend's matrix

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  id: myApi
  encryption:
    key: "3UbzqLNBqyLaO+LZVcU9JoC/4pk4qbwrH2Iwb3vyw5c="

ota:
  - platform: esphome
    password: "cd53ad04079f49087c33e1f48081ea57"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  id: myWifi

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Communicator"
    password: "MyCommPassword!"

captive_portal:

web_server:
  ota: false
  log: false
  version: 3

# blink slow: warning; blink fast: error; otherwise off
status_led:
  pin:
    number: GPIO08
    inverted: true
    ignore_strapping_warning: true

font:
  - file: "fonts/pixelmix/pixelmix.ttf"
    id: myFont
    size: 6

spi:
  clk_pin: $display_pin_clk
  mosi_pin: $display_pin_din

time:
  - platform: homeassistant
    id: myTime
    timezone: Europe/Berlin

display:
  - platform: max7219digit
    cs_pin: $display_pin_cs
    num_chips: 3
    scroll_mode: STOP
    scroll_speed: 100ms

    intensity: $display_intensity
    id: myDisplay
    lambda: |-
      if (!id(myWifi).is_connected()) {
        it.print(0, 1, id(myFont), "Online");
      // } else if (!id(myApi).is_connected()) {
      //  it.print(0, 0, id(myFont), "Load");
      } else {
        // it.print(0, -1, id(myFont), "Guten Tag");
        auto time = id(myTime).now();
        it.strftime(0, 1, id(myFont), "%H:%M", time);
      }
